### ISSUE TITLE
mphfKind is not stored in hdf5 file

### ISSUE THREAD

**Issue by Piezoid** [GATB/gatb-core#15]
Hi.

Opening a graph generated with an emphf table (for example a graph generated with Minia) trigger a segfault.

The problem is that `GraphTemplate (const std::string& uri)` initialize `_mphfKind` to `MPHF_BOOPHF`, then the map is loaded with the BooPHF implementation, triggering the crash.

I tried to implement the detection but found that mphfKind is not stored in `/configuration/xml` nor in `/mphf/xml`. `grep -i emphf` confirmed that the string is not present.

**Comment by rchikhi** [comment]
Good catch. Temporary fix: set "-mphf boophf" when running the software. 
We're getting rid of `_mphfKind` and emphf in the next release, in favor of BooPHF enabled by default in Graph.
