### ISSUE TITLE
Setting install prefix

### ISSUE THREAD

**Issue by ffranr** [GATB/gatb-core#21]
I would like to install GATB and use it as a library.
How can I specify the install prefix please?

The prefix is ignored when specified as follows: 
```
cmake --DCMAKE_INSTALL_PREFIX="/custom/prefix/" ..
make install
```

Executing `cmake DESTDIR=/home/rffrancon/Documents/pandora/cmake-build-debug install` installs to the following path: `/custom/prefix/usr/local/HDF_Group/HDF5/1.8.18`.

Thank you for your help.

**Comment by rchikhi** [comment]
Hi Robyn,

Actually it is `cmake -DCMAKE_INSTALL_PREFIX="/custom/prefix" ..` with a single dash.

Of note: we provide a simple makefile to use that installed gatb:

https://github.com/GATB/gatb-core/blob/master/gatb-core/examples/Makefile

Alternatively, we provide a way to create a new empty project that automatically compiles gatb-core using cmake:

https://github.com/GATB/gatb-core/#quickly-create-a-new-gatb-tool-software

**Comment by ffranr** [comment]
Thank you for your response @rchikhi!

Executing `cmake /custom_prefix/` produces multiple undesirable CMake build/configuration files. To get around this problem, I'm executing `cmake /tmp_prefix/` and then copying some files into `custom_prefix/`. For instance, I'm copying everything from `tmp_prefix/include`.

However, `gatb/gatb_core.hpp` is still not present in `tmp_prefix/include`. I therefore can't compile a simple example without also executing:
`cp -r ./gatb-core-1.4.1/gatb-core/src/gatb/* /custom_prefix/include/gatb/`.

Here's the bare bones example of what I mean: https://github.com/rffrancon/example_lib_gatb

(I don't think that the "new empty project" strategy is viable for us because we are working from an existing code base.)

Thank you again for your time.

**Comment by rchikhi** [comment]
The previous instructions that I wrote here before editing were incorrect, did you try the correct `cmake -DCMAKE_INSTALL_PREFIX="/custom/prefix" && make install ` procedure?

**Comment by ffranr** [comment]
As I recall, I did try with `-DCMAKE_INSTALL_PREFIX` but `gatb/gatb_core.hpp` is still missing as I describe above.

**Comment by rchikhi** [comment]
really? this is what I did:
```
cd /tmp
git clone https://github.com/GATB/gatb-core.git
cd gatb-core/gatb-core
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX="$PWD/install_prefix" && make install -j 8
ls -l install_prefix/include/gatb/gatb_core.hpp
```
```

**Comment by ffranr** [comment]
Those commands worked for me. I'm not sure what I did differently previously, I'll review.
Thank you for your help.
