### ISSUE TITLE
Depth-first search on a graph

### ISSUE THREAD

**Issue by mbhall88** [GATB/gatb-core#22]
Hi guys,

I was wondering if you could point me to an example of how to implement depth-first search on a GATB de Bruijn graph? I see in the snippets there is an implementation for BFS but I need DFS.  

In some of the slides floating around from presentations you have done it says the API provides ways of doing DFS on a graph but I am struggling to piece it together from the documentation.  

Effectively what I am trying to do is find all paths from a starting kmer to some given "end kmer". What I had thought of doing was running DFS from the start kmer and then taking all paths from that node which include my "end kmer".  

I have tried implementing DFS but have been running into issues that most likely relate to me not fully understanding the API - i.e when trying to generate paths getting stuck in unexpected (to me) cycles relating to reverse compliment kmers.

Any help is most appreciated.

**Comment by rchikhi** [comment]
Hi Michael,

Actually the reason why you'd want to do a BFS in such a case, is because doing a DFS might get you to traverse the whole graph due to repeated kmers. BFS enables to control the depth of traversal, related to genomic proximity. I.e. BFS with depth at most 1000 guarantees that you will find all paths of length at most 1000. DFS over at most, say 100,000 nodes, might get stuck following a repeated kmer and end up at a completely different location in your genome. Does that make sense?

Rayan

**Comment by mbhall88** [comment]
Hi Rayan,

Thanks for the quick response.

In my current example I *do* want to traverse the entire graph to ensure I have found every possible way of getting from my start kmer to my end kmer. Additionally, I don't expect these dBGs to be very large, they will most likely be built from sequences that should not span more than ~1000bp (in many cases will likely only be in the order of 50bp).  

Another reason we were leaning towards DFS was it's ability to detect cycles.

Michael

**Comment by rchikhi** [comment]
I see. Actually, I cannot find an example of DFS in our code, only BFS. It could be easier to just fix your current DFS code, can you paste the part regarding cycle detection?

**Comment by rchikhi** [comment]
Found some (old) code that does a simple DFS using recursion: https://github.com/GATB/gatb-core/blob/4958e3f82282b22c411f1aa148649dd34061a72c/gatb-core/src/gatb/debruijn/impl/Simplifications.cpp#L701

**Comment by mbhall88** [comment]
Thanks Rayan - I really appreciate you taking the time.  

I *think* I may have fixed my implementation. Will do some more rigorous testing on some corner cases tomorrow. If not, I will provide some code.

**Comment by rchikhi** [comment]
sure, just let us know

**Comment by mbhall88** [comment]
Yes, it seems to be working now. Apologies for taking up your time. And thank you again for your assistance.
