### ISSUE TITLE
Could not find ZLIB

### ISSUE THREAD

**Issue by dizam92** [GATB/gatb-core#24]
Hi, I try to install GATB-Core on my computer and it's keep failing due to an error i don't understand. 
It seems that CMake couldn't find ZLIB package in the the hdf5 thirdparty. 
Obviously i do have zlib install here:
/home/$1/anaconda2/include
/home/$1/anaconda2/lib/libz.so
But the Hdf5 thirdparty doesnt seems to look at it at all. 
I did try to set manually the CMAKE_PREFIX_PATH like this but it doesnt help:  cmake -D CMAKE_PREFIX_PATH="/home/$1/anaconda2/lib/" ..
> CMake Warning at thirdparty/hdf5/CMakeFilters.cmake:36 (find_package):
  Could not find a package configuration file provided by "ZLIB" with any of
  the following names:

    ZLIBConfig.cmake
    zlib-config.cmake

  Add the installation prefix of "ZLIB" to CMAKE_PREFIX_PATH or set
  "ZLIB_DIR" to a directory containing one of the above files.  If "ZLIB"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  thirdparty/hdf5/CMakeLists.txt:574 (include)

-- Found ZLIB: /home/$1/anaconda2/lib/libz.so (found version "1.2.11") 
-- Filter ZLIB is ON
DYNAMIC BINARIES for gatb-h5dump
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/$1/PycharmProjects/kover/core/kover/dataset/tools/kmer_tools/thirdparty/gatb-core/gatb-core/build

**Comment by rchikhi** [comment]
hi @dizam92, 
* Can you please post or email me (rayan.chikhi@univ-lille.fr) the full cmake error message? It seems that the issue that you posted here contains a parts of it and there are some formatting issues that prevent properly parsing it. 

* one of the lines say 'Found ZLIB: /home/$1/anaconda2/lib/libz.so (found version "1.2.11")'  as well as ' Build files have been written to: ' so it seems that cmake has finally completed without errors..

* Also is it normal that your home dir is "/home/$1" ?


Best,
Rayan

**Comment by dizam92** [comment]
Hi Rayan,
Thanks for the reply,
- It was weird but i someone told me to reinstall gcc. I did and everything is working now. The new version of gcc used is: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
- For the home directory i've just replaced my name by $1
