### ISSUE TITLE
Segmentation fault when creating de Bruijn Graph

### ISSUE THREAD

**Issue by Godotcoffee** [GATB/gatb-core#25]
Hi.
I'm using `Graph::create` to test some sequences. Then I find that in some special inputs, the lib will crash. One example is ["TCAG", "TCCA"] with kmer-size = 4. The code is in below:

`size_t kmerSize = 4;`
`IBank *bank = new BankStrings("TCAG", "TCCA", NULL);`
`Graph graph = Graph::create(bank, "-kmer-size %d -abundance-min 1 -verbose 0", kmerSize);`

There are also other inputs can cause the problem such as ['TCAGTCCA'](combine them) and ['TCCTCAG'] with kmersize = 4.

I find the crash line with GDB: 452 line, '__sync_fetch_and_or (this->blooma + (h0 >> 3), bit_mask[h0 & 7])', in function `void BloomCacheCoherent::insert (const Item& item)`, in file 'Bloom.hpp'
In the first case, h0 = 14049774491787554146

My environment:
OS: Ubuntu 18.04
CMake version: 3.10.3
gcc/g++ version: 7.3.0
Make version: 4.1
GATB-CORE version: 1.4.1

I also try clang 6.0.0 and the problem still.

What is the reason? Could this be avoided?
Thanks.

**Comment by rchikhi** [comment]
Hi!
Thanks for bringing this bug to our attention. It has been fixed, there was a problem estimating the bloom filter size for tiny kmer sizes. A new unit test has been created as a result: https://github.com/GATB/gatb-core/blob/master/gatb-core/test/unit/src/debruijn/TestDebruijn.cpp#L1287

Rayan
