### ISSUE TITLE
please create new release

### ISSUE THREAD

**Issue by osallou** [GATB/gatb-core#26]
gatb-core has not make any new release for a while.
However, minia and other tools make use of gatb code more recent than available releases, and do not build with last gatb release. Since last release, ABI has changed and code is not compatible anymore (functions with different number of parameters etc....)

Expecting to have a freezed copy of gatb in a tool subdir is not a very good practice/expectation (as set in gatbcore cmake module file).

Tools should be able to compile/link against gatb as an external lib with its include on a system.

Anyway, could you make a new stable release available ?

**Comment by rchikhi** [comment]
ta-da! easter bunny came

**Comment by mr-c** [comment]
Thank you easter bunny!
