### ISSUE TITLE
problem with <boost/graph/adjacency_list.hpp>

### ISSUE THREAD

**Issue by MinzhuXie** [GATB/gatb-core#30]
I had only inserted "#include <boost/graph/adjacency_list.hpp>" at the head of the gatb-core example file debruijn1.cpp, and type the following commands: 
      > cmake -DGATB_CORE_INCLUDE_EXAMPLES=True -DCMAKE_BUILD_TYPE=Debug ..     
      >  make -j4 debruijn1

there is a compile error: 
[100%] Building CXX object examples/CMakeFiles/debruijn1.dir/debruijn/debruijn1.cpp.o
In file included from /usr/local/include/boost/pending/container_traits.hpp:15:0,
                 from /usr/local/include/boost/graph/named_graph.hpp:23,
                 from /usr/local/include/boost/graph/adjacency_list.hpp:37,
                 from /home/xieminzhu/Downloads/GATB/gatb-core/gatb-core/examples/debruij/debruijn1.cpp:3:
/usr/local/include/boost/next_prior.hpp:64:1: error: template argument 2 is invalid
 >
 ^
  The g++ version is : gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 
  The boost installed in the Ubuntu is boost_1_71_0

**Comment by rchikhi** [comment]
Indeed I get the same issue. It doesn't look like gatb-core plays well with an external Boost dependency. This could be because gatb-core already includes another version of Boost (in `../thirdparty`). Do you really need to use boost::adjacency_list?

Best,
Rayan

**Comment by MinzhuXie** [comment]
Yes. One of my student tried to use a gatb tool Bicolor but always got a compile error with the head file.
Is there any solution to this issue?
Best,
Minzhu Xie

在 2019年10月25日，下午11:14，Rayan Chikhi <notifications@github.com<mailto:notifications@github.com>> 写道：


Indeed I get the same issue. It doesn't look like gatb-core plays well with an external Boost dependency. This could be because gatb-core already includes another version of Boost (in ../thirdparty). Do you really need to use boost::adjacency_list?

Best,
Rayan

**Comment by rchikhi** [comment]
Sorry for the delay, it should work now in the latest version of the master branch.
