### ISSUE TITLE
Gatb-core v1.2.1 does not compile on old clang

### ISSUE THREAD

**Issue by clemaitre** [GATB/gatb-core#8]
Hi, 

Problem of compilation with new version of gatb-core v1.2.1 : something related to `struct hash` in `LargeInt.hpp` (commit 6d9525e89b8cb8e3b15dda32f6d2086333e27b01)
Compiler : clang 4.1 on mac

```
LargeInt.hpp:870:10: error: no template named 'hash'; did you mean 'boost::hash'? struct hash< gatb::core::tools::math::LargeInt<precision> >

Simplifications.hpp:76:96: error: use of undeclared identifier 'nullptr'
                                unsigned int backtrackingLimit = 0, Node *avoidFirstNode = nullptr,
```

**Comment by rchikhi** [comment]
could you please give it a try with the latest commit on the master branch?

**Comment by clemaitre** [comment]
still 1 error, but a different one:
`Graph.cpp:3737:33: error: expected expression dispatcher.iterate (itNode, [&] (Node& node)        {`

**Comment by rchikhi** [comment]
okay, fixing them one at a time.. try now?

**Comment by clemaitre** [comment]
Sorry Rayan for the delayed answer.. it works fine now ! Thank you for maintaining a little longer the compatibility with old compilers :-)

**Comment by rchikhi** [comment]
cool, thanks for testing!
